# Chapter 2 Regression and model validation

11.11.2019
*Describe the work you have done this week and summarize your learning.*

**work through the DataCamp:**

DataCamp 3 Regression and model validation

**2.1 Data wrangling**

*read the data into memory*

lrn14 <- read.table("https://www.mv.helsinki.fi/home/kvehkala/JYTmooc/JYTOPKYS3-data.txt", sep="\t", header=JYTOPKYS3-data)

**Step 1**
*Create the ‘data’ folder and new R script*


**Step 2a**
*Look at the dimensions of the data*

dim(lrn14)


**Step 2b**
*Look at the structure of the data*

str(lrn14)

**data.frame: 183 obs. of 60 variables**

**gender  : Factor w/ 2 levels "F","M"**

**other variables (Age, Attitude, Points, Aa, ... , ST01, ...): int**


**Step 3a**
*Create an analysis dataset with the 7 variables*

library(dplyr)

keep_columns <- c("gender","age","attitude", "deep", "stra", "surf", "points")

learning2014 <- select(lrn14, one_of(keep_columns))

learning2014


**Step 3b**
*Scale all combination variables to the original scales*

deep_questions <- c("D03", "D11", "D19", "D27", "D07", "D14", "D22", "D30","D06",  "D15", "D23", "D31")

strategic_questions <- c("ST01","ST09","ST17","ST25","ST04","ST12","ST20","ST28")

surface_questions <- c("SU02","SU10","SU18","SU26", "SU05","SU13","SU21","SU29","SU08","SU16","SU24","SU32")

deep_columns <- select(lrn14, one_of(deep_questions))
lrn14$deep <- rowMeans(deep_columns)

strategic_columns <- select(lrn14, one_of(strategic_questions))

lrn14$str <- rowMeans(strategic_columns)

surface_columns <- select(lrn14, one_of(surface_questions))

lrn14$surf <- rowMeans(surface_columns)


**Step 3c**
*Exclude observations where the exam points variable is zero*

learning2014 <- filter(learning2014, points > 0)

**Step 4**
*Save in the iods project folder*


**2.2 Analysis**


